name: Dependency Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight UTC

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install npm packages
        run: |
          if [ -f package.json ]; then
            npm install
          else
            echo "No package.json found, skipping npm install."
          fi

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the Python version you need

      - name: Install Python packages
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found, skipping pip install."
          fi

      - name: Run npm audit
        continue-on-error: true
        run: |
          if [ -f package.json ]; then
            npm audit
          else
            echo "No package-lock.json found, skipping npm audit."
          fi

      - name: Run pip-audit
        continue-on-error: true
        run: |
          if [ -f requirements.txt ]; then
            pip-audit -r requirements.txt
          else
            echo "No requirements.txt found, skipping pip-audit."
          fi